import { v4 as uuidv4 } from "uuid";
import type { Client } from "./types";

/**
 * Pre-configured client list for CS Design Studios.
 * WordPress credentials need to be added via the dashboard.
 */
export const SEED_CLIENTS: Omit<Client, "id" | "createdAt" | "updatedAt">[] = [
  {
    name: "Altitude Home Loans",
    businessName: "Altitude Home Loans",
    industry: "Mortgage & Home Loans",
    targetAudience: "Homebuyers and refinancers",
    location: "Arizona",
    websiteUrl: "https://altitudehomeloans.com",
    wordpressUrl: "https://altitudehomeloans.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "professional",
    keywords: ["home loans", "mortgage rates", "refinancing", "first-time homebuyer"],
    blogCategories: ["Mortgage Tips", "Home Buying", "Refinancing"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Arizona Uniform",
    businessName: "Arizona Uniform",
    industry: "Uniform & Workwear",
    targetAudience: "Businesses needing uniforms and workwear",
    location: "Arizona",
    websiteUrl: "https://arizonauniform.com",
    wordpressUrl: "https://arizonauniform.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "professional",
    keywords: ["work uniforms", "custom uniforms", "corporate workwear"],
    blogCategories: ["Uniforms", "Workwear Tips", "Industry News"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Bob's Custom Roofing",
    businessName: "Bob's Custom Roofing",
    industry: "Roofing",
    targetAudience: "Homeowners needing roofing services",
    location: "Arizona",
    websiteUrl: "https://bobscustomroofing.com",
    wordpressUrl: "https://bobscustomroofing.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "friendly",
    keywords: ["roof repair", "custom roofing", "roof replacement", "roofing contractor"],
    blogCategories: ["Roofing Tips", "Home Maintenance", "Roofing Services"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "CAMCO",
    businessName: "CAMCO",
    industry: "Property Management",
    targetAudience: "HOA communities and property owners",
    location: "Arizona",
    websiteUrl: "https://camcoaz.com",
    wordpressUrl: "https://camcoaz.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "professional",
    keywords: ["property management", "HOA management", "community management"],
    blogCategories: ["Property Management", "HOA Tips", "Community Living"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Connect Security",
    businessName: "Connect Security",
    industry: "Security Systems",
    targetAudience: "Homeowners and businesses seeking security solutions",
    location: "Arizona",
    websiteUrl: "https://connectsecurity.com",
    wordpressUrl: "https://connectsecurity.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "authoritative",
    keywords: ["home security", "security systems", "surveillance cameras", "alarm systems"],
    blogCategories: ["Security Tips", "Home Safety", "Business Security"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "CS Design Studios",
    businessName: "CS Design Studios",
    industry: "Digital Marketing & Web Design",
    targetAudience: "Small businesses needing digital marketing",
    location: "Arizona",
    websiteUrl: "https://csdesignstudios.com",
    wordpressUrl: "https://csdesignstudios.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "professional",
    keywords: ["web design", "digital marketing", "SEO services", "social media marketing"],
    blogCategories: ["Marketing Tips", "Web Design", "SEO", "Social Media"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Cutting Edge Collision",
    businessName: "Cutting Edge Collision",
    industry: "Auto Body Repair",
    targetAudience: "Vehicle owners needing collision repair",
    location: "Arizona",
    websiteUrl: "https://cuttingedgeref.com",
    wordpressUrl: "https://cuttingedgeref.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "friendly",
    keywords: ["collision repair", "auto body shop", "car dent repair", "paint repair"],
    blogCategories: ["Auto Repair", "Car Care Tips", "Collision Services"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Easy Breezy",
    businessName: "Easy Breezy",
    industry: "HVAC",
    targetAudience: "Homeowners needing AC and heating services",
    location: "Arizona",
    websiteUrl: "https://easybreezeyheat-ac.com",
    wordpressUrl: "https://easybreezeyheat-ac.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "friendly",
    keywords: ["AC repair", "HVAC service", "air conditioning", "heating repair"],
    blogCategories: ["HVAC Tips", "Home Comfort", "Energy Efficiency"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Elite Wildlife",
    businessName: "Elite Wildlife Solutions",
    industry: "Wildlife Removal",
    targetAudience: "Homeowners dealing with wildlife issues",
    location: "Georgia",
    websiteUrl: "https://elitewildlifesolutionsga.com",
    wordpressUrl: "https://elitewildlifesolutionsga.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "authoritative",
    keywords: ["wildlife removal", "pest control", "animal removal", "wildlife management"],
    blogCategories: ["Wildlife Control", "Prevention Tips", "Local Wildlife"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Formula 1 Collision",
    businessName: "Formula 1 Collision",
    industry: "Auto Body Repair",
    targetAudience: "Vehicle owners needing collision and body work",
    location: "Arizona",
    websiteUrl: "https://formula1collision.com",
    wordpressUrl: "https://formula1collision.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "professional",
    keywords: ["auto body repair", "collision center", "car restoration", "paint correction"],
    blogCategories: ["Auto Repair", "Car Care", "Collision Services"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Greer Painting",
    businessName: "Nelson Greer Painting",
    industry: "Painting Services",
    targetAudience: "Homeowners and businesses needing painting",
    location: "Arizona",
    websiteUrl: "https://nelsongreerpainting.com",
    wordpressUrl: "https://nelsongreerpainting.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "friendly",
    keywords: ["house painting", "commercial painting", "interior painting", "exterior painting"],
    blogCategories: ["Painting Tips", "Home Improvement", "Color Ideas"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "GLW Shows",
    businessName: "GLW Shows",
    industry: "Events & Shows",
    targetAudience: "Event attendees and exhibitors",
    location: "Arizona",
    websiteUrl: "https://glwshows.com",
    wordpressUrl: "https://glwshows.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "conversational",
    keywords: ["trade shows", "events", "exhibitions", "gun shows"],
    blogCategories: ["Events", "Show Calendar", "Exhibitor Tips"],
    postsPerMonth: 2,
    isActive: true,
  },
  {
    name: "Hook Crane",
    businessName: "Hook Crane",
    industry: "Crane Services",
    targetAudience: "Construction companies and contractors",
    location: "Arizona",
    websiteUrl: "https://hookcrane.com",
    wordpressUrl: "https://hookcrane.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "professional",
    keywords: ["crane rental", "crane services", "heavy lifting", "construction crane"],
    blogCategories: ["Crane Services", "Construction", "Safety"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Joe's Yard and Tree",
    businessName: "Joe's Yard and Tree",
    industry: "Landscaping & Tree Service",
    targetAudience: "Homeowners needing yard and tree services",
    location: "Arizona",
    websiteUrl: "https://joes-yard.com",
    wordpressUrl: "https://joes-yard.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "friendly",
    keywords: ["tree trimming", "yard maintenance", "landscaping", "tree removal"],
    blogCategories: ["Landscaping Tips", "Tree Care", "Yard Maintenance"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Little Germany",
    businessName: "Little Germany",
    industry: "Restaurant & Food",
    targetAudience: "Diners and food enthusiasts",
    location: "Tucson, Arizona",
    websiteUrl: "https://littlegermanytucson.com",
    wordpressUrl: "https://littlegermanytucson.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "conversational",
    keywords: ["German restaurant", "German food", "authentic cuisine", "beer garden"],
    blogCategories: ["Food & Drink", "German Culture", "Events"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "OnGuard Pest Control",
    businessName: "OnGuard Pest Control",
    industry: "Pest Control",
    targetAudience: "Homeowners and businesses dealing with pests",
    location: "Arizona",
    websiteUrl: "https://onguardpest.com",
    wordpressUrl: "https://onguardpest.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "authoritative",
    keywords: ["pest control", "exterminator", "termite treatment", "bug removal"],
    blogCategories: ["Pest Control", "Prevention Tips", "Home Protection"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Optical Perspectives",
    businessName: "Optical Perspectives",
    industry: "Eye Care & Optometry",
    targetAudience: "Patients seeking eye care and eyewear",
    location: "Arizona",
    websiteUrl: "https://opticalperspectives.com",
    wordpressUrl: "https://opticalperspectives.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "professional",
    keywords: ["eye exam", "eyeglasses", "contact lenses", "optometrist"],
    blogCategories: ["Eye Health", "Eyewear", "Vision Care"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Osser Communications",
    businessName: "Osser Communications",
    industry: "Telecommunications",
    targetAudience: "Businesses needing communication solutions",
    location: "Arizona",
    websiteUrl: "https://osercomm.com",
    wordpressUrl: "https://osercomm.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "professional",
    keywords: ["business phones", "VoIP", "telecommunications", "unified communications"],
    blogCategories: ["Telecom", "Business Solutions", "Technology"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Pro Remodeling",
    businessName: "Pro Remodeling",
    industry: "Home Remodeling",
    targetAudience: "Homeowners planning renovations",
    location: "Arizona",
    websiteUrl: "https://pro-remodeling.com",
    wordpressUrl: "https://pro-remodeling.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "professional",
    keywords: ["kitchen remodel", "bathroom remodel", "home renovation", "general contractor"],
    blogCategories: ["Remodeling", "Home Improvement", "Design Ideas"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Rose Academies",
    businessName: "Rose Academies",
    industry: "Education",
    targetAudience: "Parents and students seeking education programs",
    location: "Arizona",
    websiteUrl: "https://go2rose.com",
    wordpressUrl: "https://go2rose.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "professional",
    keywords: ["charter school", "education", "student programs", "academic excellence"],
    blogCategories: ["Education", "Student Life", "Academics"],
    postsPerMonth: 2,
    isActive: true,
  },
  {
    name: "Santa Cruz Vet",
    businessName: "Santa Cruz Vet",
    industry: "Veterinary Care",
    targetAudience: "Pet owners seeking veterinary services",
    location: "Arizona",
    websiteUrl: "https://santacruzpet.com",
    wordpressUrl: "https://santacruzpet.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "friendly",
    keywords: ["veterinarian", "pet care", "animal hospital", "vet clinic"],
    blogCategories: ["Pet Health", "Pet Care Tips", "Veterinary Services"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Santa Rita Landscaping",
    businessName: "Santa Rita Landscaping",
    industry: "Landscaping",
    targetAudience: "Homeowners and businesses needing landscaping",
    location: "Arizona",
    websiteUrl: "https://santaritalandscaping.com",
    wordpressUrl: "https://santaritalandscaping.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "friendly",
    keywords: ["landscaping", "desert landscaping", "lawn care", "outdoor design"],
    blogCategories: ["Landscaping", "Garden Tips", "Outdoor Living"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Silicon Pools AZ",
    businessName: "Silicon Pools AZ",
    industry: "Pool Services",
    targetAudience: "Pool owners and homeowners wanting pools",
    location: "Arizona",
    websiteUrl: "https://siliconpoolsaz.com",
    wordpressUrl: "https://siliconpoolsaz.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "friendly",
    keywords: ["pool cleaning", "pool maintenance", "pool installation", "pool repair"],
    blogCategories: ["Pool Care", "Pool Design", "Maintenance Tips"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "SWIBA",
    businessName: "SWIBA",
    industry: "Business Association",
    targetAudience: "Local business owners and entrepreneurs",
    location: "Arizona",
    websiteUrl: "https://swibadonor.org",
    wordpressUrl: "https://swibadonor.org",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "professional",
    keywords: ["business association", "networking", "small business", "local business"],
    blogCategories: ["Business News", "Networking", "Member Spotlights"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Wiese Painting",
    businessName: "Wiese Painting",
    industry: "Painting Services",
    targetAudience: "Homeowners and businesses needing painting",
    location: "Arizona",
    websiteUrl: "https://wiesepainting.com",
    wordpressUrl: "https://wiesepainting.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "friendly",
    keywords: ["house painting", "commercial painting", "interior painting", "exterior painting"],
    blogCategories: ["Painting Tips", "Home Improvement", "Color Trends"],
    postsPerMonth: 1,
    isActive: true,
  },
  {
    name: "Wilkey Pest Control",
    businessName: "Wilkey Pest Control",
    industry: "Pest Control",
    targetAudience: "Homeowners and businesses dealing with pests",
    location: "Arizona",
    websiteUrl: "https://www.wilkeyservices.com",
    wordpressUrl: "https://www.wilkeyservices.com",
    wordpressUsername: "",
    wordpressAppPassword: "",
    seoNotes: "",
    tone: "friendly",
    keywords: ["pest control", "exterminator", "pest removal", "pest prevention"],
    blogCategories: ["Pest Control", "Prevention Tips", "Seasonal Pests"],
    postsPerMonth: 1,
    isActive: true,
  },
];

export function createSeededClients(): Client[] {
  const now = new Date().toISOString();
  return SEED_CLIENTS.map((seed) => ({
    ...seed,
    id: uuidv4(),
    createdAt: now,
    updatedAt: now,
  }));
}
