<?php
/**
 * Plugin Name:  CS Publisher
 * Description:  Secure REST endpoint for the CS Design Studios monthly-blogs dashboard.
 *               Lets the dashboard publish blog posts to this WordPress site without
 *               needing an Application Password. Works even when Wordfence has
 *               Application Passwords disabled.
 * Version:      1.2.1
 * Author:       CS Design Studios
 * Author URI:   https://csdesignstudios.com
 *
 * ─── How this plugin was installed ──────────────────────────────────────────
 * This file was generated by the CS Design Studios monthly-blogs dashboard.
 * The secret key below is unique to this site. Do not share this file.
 * To rotate the secret, download a new installer from the dashboard and
 * re-upload it here (Plugins → Add New → Upload Plugin).
 */

if (!defined('ABSPATH')) exit;

// These defines are injected by the dashboard installer — do not rename them.
define('CS_PUBLISHER_SECRET', '__CS_PUBLISHER_SECRET__');
define('CS_PUBLISHER_USER_ID', 0);

// Versioned class name — BUMP THIS on EVERY release (v1 -> v1_2 -> v1_3 ...).
// It must differ from every previously shipped name. Reason: an older copy can
// still be present and load FIRST (e.g. a stale must-use plugin in
// wp-content/mu-plugins/, which WordPress loads before normal plugins). If both
// copies used the same class name, class_exists() would make the first-loaded
// (older) copy win and this newer one would be silently skipped. A unique name
// guarantees this copy's class is always defined, and the routes below register
// with override=true so the newest loaded copy always handles requests.
if (!class_exists('CS_Publisher_v1_2')) :

class CS_Publisher_v1_2 {

    const VERSION = '1.2.1';

    public function __construct() {
        add_action('admin_menu',    [$this, 'register_settings_page']);
        add_action('rest_api_init', [$this, 'register_routes']);
    }

    // ─── Admin settings page ─────────────────────────────────────────────────

    public function register_settings_page() {
        add_options_page('CS Publisher', 'CS Publisher', 'manage_options', 'cs-publisher', [$this, 'render_settings_page']);
    }

    public function render_settings_page() {
        $secret     = CS_PUBLISHER_SECRET;
        $configured = $secret && $secret !== '__CS_PUBLISHER_SECRET__';
        $user_id    = (int) CS_PUBLISHER_USER_ID;
        if ($user_id <= 0) {
            $admins  = get_users(['role' => 'administrator', 'number' => 1, 'orderby' => 'ID', 'order' => 'ASC', 'fields' => 'ID']);
            $user_id = !empty($admins) ? (int)$admins[0] : 0;
        }
        $user = $user_id ? get_user_by('id', $user_id) : null;
        ?>
        <div class="wrap">
            <h1>CS Publisher <span style="font-size:13px;font-weight:normal;color:#777;">v<?php echo esc_html(self::VERSION); ?></span></h1>
            <table class="form-table" role="presentation">
                <tr>
                    <th scope="row">Status</th>
                    <td>
                        <?php if ($configured): ?>
                            <span style="color:#46b450;font-weight:600;">Active — secret configured</span>
                        <?php else: ?>
                            <span style="color:#dc3232;font-weight:600;">Not configured — re-download installer from the dashboard</span>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php if ($user): ?>
                <tr>
                    <th scope="row">Publishing as</th>
                    <td>
                        <strong><?php echo esc_html($user->user_login); ?></strong>
                        (User #<?php echo esc_html((string)$user_id); ?>)
                    </td>
                </tr>
                <?php endif; ?>
                <tr>
                    <th scope="row">Test endpoint</th>
                    <td><code><?php echo esc_html(rest_url('cs-publisher/v1/ping')); ?></code></td>
                </tr>
                <tr>
                    <th scope="row">Publish endpoint</th>
                    <td><code><?php echo esc_html(rest_url('cs-publisher/v1/publish')); ?></code></td>
                </tr>
            </table>
            <p style="color:#777;margin-top:20px;font-size:13px;">
                To rotate the secret or fix a connection issue, go to the CS Design Studios dashboard,
                click <strong>Download Installer</strong> for this site, and re-upload the zip here
                (Plugins → Add New → Upload Plugin → check "Replace current with uploaded version").
            </p>
        </div>
        <?php
    }

    // ─── REST routes ─────────────────────────────────────────────────────────

    public function register_routes() {
        // override=true (4th arg): if a stale older copy already registered
        // these routes (it loads first as a must-use plugin), replace them so
        // the newest installed copy always handles requests.
        register_rest_route('cs-publisher/v1', '/publish', [
            'methods'             => 'POST',
            'callback'            => [$this, 'handle_publish'],
            'permission_callback' => [$this, 'check_secret'],
        ], true);
        register_rest_route('cs-publisher/v1', '/ping', [
            'methods'             => 'GET',
            'callback'            => [$this, 'handle_ping'],
            'permission_callback' => [$this, 'check_secret'],
        ], true);
    }

    // ─── Authentication ───────────────────────────────────────────────────────

    public function check_secret(WP_REST_Request $req) {
        $secret = CS_PUBLISHER_SECRET;
        if (!$secret || $secret === '__CS_PUBLISHER_SECRET__') {
            return new WP_Error('cs_publisher_unconfigured', 'CS_PUBLISHER_SECRET not configured — re-download installer from the dashboard', ['status' => 500]);
        }
        $provided = (string)$req->get_header('x-cs-secret');
        if ($provided === '') {
            $provided = (string)$req->get_param('cs_secret');
        }
        if (!$provided || !hash_equals((string)$secret, $provided)) {
            return new WP_Error('cs_publisher_unauthorized', 'Invalid or missing secret', ['status' => 401]);
        }
        $user_id = (int) CS_PUBLISHER_USER_ID;
        if ($user_id <= 0) {
            $admins  = get_users(['role' => 'administrator', 'number' => 1, 'orderby' => 'ID', 'order' => 'ASC', 'fields' => 'ID']);
            $user_id = !empty($admins) ? (int)$admins[0] : 0;
        }
        if ($user_id <= 0) {
            return new WP_Error('cs_publisher_no_admin', 'No administrator user found on this site', ['status' => 500]);
        }
        wp_set_current_user($user_id);
        return true;
    }

    // ─── Ping ─────────────────────────────────────────────────────────────────

    public function handle_ping(WP_REST_Request $req) {
        $user = wp_get_current_user();
        return new WP_REST_Response([
            'ok'         => true,
            'version'    => self::VERSION,
            'user_id'    => (int)$user->ID,
            'user_login' => $user->user_login,
            'user_roles' => array_values($user->roles),
        ], 200);
    }

    // ─── Shared: sideload + set featured image ────────────────────────────────

    /**
     * Download (or decode) an image and set it as the post's featured image.
     *
     * @param int    $post_id   WordPress post ID to attach the image to.
     * @param string $filename  Desired filename for the media attachment.
     * @param string $alt_text  Image alt text (written to _wp_attachment_image_alt).
     * @param string $img_url   URL to download the image from (used when $img_b64 is empty).
     * @param string $img_b64   Base64-encoded image bytes (preferred — skips the HTTP download).
     *
     * Returns true on success, a WP_Error on failure.
     */
    private function set_featured_image($post_id, $filename, $alt_text = '', $img_url = '', $img_b64 = '') {
        require_once ABSPATH . 'wp-admin/includes/file.php';
        require_once ABSPATH . 'wp-admin/includes/media.php';
        require_once ABSPATH . 'wp-admin/includes/image.php';

        if ($img_b64 !== '') {
            $decoded = base64_decode($img_b64, true);
            if ($decoded === false) {
                return new WP_Error('cs_publisher_bad_base64', 'featured_image.data is not valid base64');
            }
            $tmp = wp_tempnam($filename);
            if (file_put_contents($tmp, $decoded) === false) {
                return new WP_Error('cs_publisher_tmp_write', 'Could not write temp file for image');
            }
        } else {
            if ($img_url === '') {
                return new WP_Error('cs_publisher_no_image_source', 'No image URL or base64 data provided');
            }
            $tmp = download_url($img_url, 60);
            if (is_wp_error($tmp)) return $tmp;
        }

        $file_array    = ['name' => $filename, 'tmp_name' => $tmp];
        $attachment_id = media_handle_sideload($file_array, $post_id);
        if (is_wp_error($attachment_id)) {
            @unlink($tmp);
            return $attachment_id;
        }
        set_post_thumbnail($post_id, $attachment_id);
        if ($alt_text !== '') {
            update_post_meta($attachment_id, '_wp_attachment_image_alt', sanitize_text_field($alt_text));
        }
        return true;
    }

    // ─── Publish (create new post OR update existing OR image-only update) ────

    public function handle_publish(WP_REST_Request $req) {
        $data = $req->get_json_params();
        if (!is_array($data)) {
            return new WP_Error('cs_publisher_bad_body', 'JSON body required', ['status' => 400]);
        }

        $existing_id       = isset($data['post_id']) ? (int)$data['post_id'] : 0;
        $update_image_only = !empty($data['update_image_only']);

        // Image-only update — just swap the featured image on an existing post.
        if ($existing_id > 0 && $update_image_only) {
            $post = get_post($existing_id);
            if (!$post) {
                return new WP_Error('cs_publisher_not_found', "Post {$existing_id} not found", ['status' => 404]);
            }
            $img      = isset($data['featured_image']) && is_array($data['featured_image']) ? $data['featured_image'] : [];
            $img_url  = isset($img['url'])  && is_string($img['url'])  ? (string)$img['url']  : '';
            $img_b64  = isset($img['data']) && is_string($img['data']) ? (string)$img['data'] : '';
            $filename = isset($img['filename']) ? (string)$img['filename'] : "featured-{$existing_id}.jpg";
            $alt_text = isset($img['alt'])      ? (string)$img['alt']      : '';

            if ($img_url !== '' || $img_b64 !== '') {
                $result = $this->set_featured_image($existing_id, $filename, $alt_text, $img_url, $img_b64);
                if (is_wp_error($result)) {
                    return new WP_Error(
                        'cs_publisher_image_failed',
                        $result->get_error_message(),
                        ['status' => 500]
                    );
                }
            } else {
                return new WP_Error('cs_publisher_no_image', 'featured_image.url or featured_image.data is required', ['status' => 400]);
            }

            return new WP_REST_Response([
                'id'      => $existing_id,
                'link'    => get_permalink($existing_id),
                'status'  => $post->post_status,
                'updated' => true,
            ], 200);
        }

        // Full publish / update — categories first.
        $category_ids = [];
        foreach ((array)(isset($data['categories']) ? $data['categories'] : []) as $name) {
            $name = (string)$name;
            if ($name === '') continue;
            $term = get_term_by('name', $name, 'category');
            if ($term && !is_wp_error($term)) {
                $category_ids[] = (int)$term->term_id;
            } else {
                $inserted = wp_insert_term($name, 'category');
                if (!is_wp_error($inserted) && isset($inserted['term_id'])) {
                    $category_ids[] = (int)$inserted['term_id'];
                }
            }
        }

        $allowed_statuses = ['publish', 'draft', 'pending', 'private'];
        $raw_status       = isset($data['status']) ? (string)$data['status'] : 'publish';
        $status           = in_array($raw_status, $allowed_statuses, true) ? $raw_status : 'publish';

        $post_data = [
            'post_title'    => wp_strip_all_tags(isset($data['title'])   ? (string)$data['title']   : ''),
            'post_name'     => sanitize_title(isset($data['slug'])        ? (string)$data['slug']    : ''),
            'post_content'  => isset($data['content'])  ? (string)$data['content']  : '',
            'post_excerpt'  => isset($data['excerpt'])  ? (string)$data['excerpt']  : '',
            'post_status'   => $status,
            'post_type'     => 'post',
            'post_author'   => get_current_user_id(),
            'post_category' => $category_ids,
            'tags_input'    => array_values(array_filter(array_map('strval', (array)(isset($data['tags']) ? $data['tags'] : [])))),
        ];

        if ($existing_id > 0) {
            $post_data['ID'] = $existing_id;
        }

        $post_id = wp_insert_post($post_data, true);
        if (is_wp_error($post_id)) {
            return new WP_Error('cs_publisher_insert_failed', $post_id->get_error_message(), ['status' => 500]);
        }

        foreach ((array)(isset($data['meta']) ? $data['meta'] : []) as $k => $v) {
            if (!is_string($k) || $k === '') continue;
            update_post_meta($post_id, $k, is_string($v) ? $v : wp_json_encode($v));
        }

        $img      = isset($data['featured_image']) && is_array($data['featured_image']) ? $data['featured_image'] : [];
        $img_url  = isset($img['url'])  && is_string($img['url'])  ? (string)$img['url']  : '';
        $img_b64  = isset($img['data']) && is_string($img['data']) ? (string)$img['data'] : '';
        $filename = isset($img['filename']) && $img['filename'] !== ''
            ? (string)$img['filename']
            : (sanitize_title(isset($data['slug']) ? (string)$data['slug'] : 'featured') . '.jpg');
        $alt_text = isset($img['alt']) ? (string)$img['alt'] : '';
        if ($img_url !== '' || $img_b64 !== '') {
            $this->set_featured_image($post_id, $filename, $alt_text, $img_url, $img_b64);
        }

        $post = get_post($post_id);
        return new WP_REST_Response([
            'id'     => (int)$post_id,
            'link'   => get_permalink($post_id),
            'status' => $post ? $post->post_status : $status,
        ], 200);
    }
}

new CS_Publisher_v1_2();

endif; // class_exists('CS_Publisher_v1_2')
