<?php
/**
 * Plugin Name:  CS Publisher
 * Description:  Secure REST endpoint for the CS Design Studios monthly-blogs dashboard.
 *               Lets the dashboard publish blog posts to this WordPress site without
 *               needing an Application Password. Works even when Wordfence has
 *               Application Passwords disabled.
 * Version:      1.1.0
 * Author:       CS Design Studios
 * Author URI:   https://csdesignstudios.com
 *
 * ─── How this plugin was installed ──────────────────────────────────────────
 * This file was generated by the CS Design Studios monthly-blogs dashboard.
 * The secret key below is unique to this site. Do not share this file.
 * To rotate the secret, download a new installer from the dashboard and
 * re-upload it here (Plugins → Add New → Upload Plugin).
 */

if (!defined('ABSPATH')) exit;

// These defines are injected by the dashboard installer — do not rename them.
define('CS_PUBLISHER_SECRET', '__CS_PUBLISHER_SECRET__');
define('CS_PUBLISHER_USER_ID', 0);

// Use a versioned class name so re-installing over an old copy never causes
// duplicate-function fatal errors. The class registers everything on instantiation.
if (!class_exists('CS_Publisher_v1')) :

class CS_Publisher_v1 {

    const VERSION = '1.1.0';

    public function __construct() {
        add_action('admin_menu',    [$this, 'register_settings_page']);
        add_action('rest_api_init', [$this, 'register_routes']);
    }

    // ─── Admin settings page ─────────────────────────────────────────────────

    public function register_settings_page() {
        add_options_page('CS Publisher', 'CS Publisher', 'manage_options', 'cs-publisher', [$this, 'render_settings_page']);
    }

    public function render_settings_page() {
        $secret     = CS_PUBLISHER_SECRET;
        $configured = $secret && $secret !== '__CS_PUBLISHER_SECRET__';
        $user_id    = (int) CS_PUBLISHER_USER_ID;
        if ($user_id <= 0) {
            $admins  = get_users(['role' => 'administrator', 'number' => 1, 'orderby' => 'ID', 'order' => 'ASC', 'fields' => 'ID']);
            $user_id = !empty($admins) ? (int)$admins[0] : 0;
        }
        $user = $user_id ? get_user_by('id', $user_id) : null;
        ?>
        <div class="wrap">
            <h1>CS Publisher <span style="font-size:13px;font-weight:normal;color:#777;">v<?php echo esc_html(self::VERSION); ?></span></h1>
            <table class="form-table" role="presentation">
                <tr>
                    <th scope="row">Status</th>
                    <td>
                        <?php if ($configured): ?>
                            <span style="color:#46b450;font-weight:600;">Active — secret configured</span>
                        <?php else: ?>
                            <span style="color:#dc3232;font-weight:600;">Not configured — re-download installer from the dashboard</span>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php if ($user): ?>
                <tr>
                    <th scope="row">Publishing as</th>
                    <td>
                        <strong><?php echo esc_html($user->user_login); ?></strong>
                        (User #<?php echo esc_html((string)$user_id); ?>)
                    </td>
                </tr>
                <?php endif; ?>
                <tr>
                    <th scope="row">Test endpoint</th>
                    <td><code><?php echo esc_html(rest_url('cs-publisher/v1/ping')); ?></code></td>
                </tr>
                <tr>
                    <th scope="row">Publish endpoint</th>
                    <td><code><?php echo esc_html(rest_url('cs-publisher/v1/publish')); ?></code></td>
                </tr>
            </table>
            <p style="color:#777;margin-top:20px;font-size:13px;">
                To rotate the secret or fix a connection issue, go to the CS Design Studios dashboard,
                click <strong>Download Installer</strong> for this site, and re-upload the zip here
                (Plugins → Add New → Upload Plugin → check "Replace current with uploaded version").
            </p>
        </div>
        <?php
    }

    // ─── REST routes ─────────────────────────────────────────────────────────

    public function register_routes() {
        register_rest_route('cs-publisher/v1', '/publish', [
            'methods'             => 'POST',
            'callback'            => [$this, 'handle_publish'],
            'permission_callback' => [$this, 'check_secret'],
        ]);
        register_rest_route('cs-publisher/v1', '/ping', [
            'methods'             => 'GET',
            'callback'            => [$this, 'handle_ping'],
            'permission_callback' => [$this, 'check_secret'],
        ]);
    }

    // ─── Authentication ───────────────────────────────────────────────────────

    public function check_secret(WP_REST_Request $req) {
        $secret = CS_PUBLISHER_SECRET;
        if (!$secret || $secret === '__CS_PUBLISHER_SECRET__') {
            return new WP_Error('cs_publisher_unconfigured', 'CS_PUBLISHER_SECRET not configured — re-download installer from the dashboard', ['status' => 500]);
        }
        $provided = (string)$req->get_header('x-cs-secret');
        if ($provided === '') {
            $provided = (string)$req->get_param('cs_secret');
        }
        if (!$provided || !hash_equals((string)$secret, $provided)) {
            return new WP_Error('cs_publisher_unauthorized', 'Invalid or missing secret', ['status' => 401]);
        }
        $user_id = (int) CS_PUBLISHER_USER_ID;
        if ($user_id <= 0) {
            $admins  = get_users(['role' => 'administrator', 'number' => 1, 'orderby' => 'ID', 'order' => 'ASC', 'fields' => 'ID']);
            $user_id = !empty($admins) ? (int)$admins[0] : 0;
        }
        if ($user_id <= 0) {
            return new WP_Error('cs_publisher_no_admin', 'No administrator user found on this site', ['status' => 500]);
        }
        wp_set_current_user($user_id);
        return true;
    }

    // ─── Ping ─────────────────────────────────────────────────────────────────

    public function handle_ping(WP_REST_Request $req) {
        $user = wp_get_current_user();
        return new WP_REST_Response([
            'ok'         => true,
            'version'    => self::VERSION,
            'user_id'    => (int)$user->ID,
            'user_login' => $user->user_login,
            'user_roles' => array_values($user->roles),
        ], 200);
    }

    // ─── Shared: sideload + set featured image ────────────────────────────────

    private function set_featured_image($post_id, $img_url, $filename, $alt_text = '') {
        require_once ABSPATH . 'wp-admin/includes/file.php';
        require_once ABSPATH . 'wp-admin/includes/media.php';
        require_once ABSPATH . 'wp-admin/includes/image.php';
        $tmp = download_url($img_url, 60);
        if (is_wp_error($tmp)) return;
        $file_array    = ['name' => $filename, 'tmp_name' => $tmp];
        $attachment_id = media_handle_sideload($file_array, $post_id);
        if (!is_wp_error($attachment_id)) {
            set_post_thumbnail($post_id, $attachment_id);
            if ($alt_text !== '') {
                update_post_meta($attachment_id, '_wp_attachment_image_alt', sanitize_text_field($alt_text));
            }
        } else {
            @unlink($tmp);
        }
    }

    // ─── Publish (create new post OR update existing OR image-only update) ────

    public function handle_publish(WP_REST_Request $req) {
        $data = $req->get_json_params();
        if (!is_array($data)) {
            return new WP_Error('cs_publisher_bad_body', 'JSON body required', ['status' => 400]);
        }

        $existing_id       = isset($data['post_id']) ? (int)$data['post_id'] : 0;
        $update_image_only = !empty($data['update_image_only']);

        // Image-only update — just swap the featured image on an existing post.
        if ($existing_id > 0 && $update_image_only) {
            $post = get_post($existing_id);
            if (!$post) {
                return new WP_Error('cs_publisher_not_found', "Post {$existing_id} not found", ['status' => 404]);
            }
            $img_url = isset($data['featured_image']['url']) ? $data['featured_image']['url'] : null;
            if (is_string($img_url) && $img_url !== '') {
                $filename = isset($data['featured_image']['filename']) ? (string)$data['featured_image']['filename'] : "pexels-{$existing_id}.jpg";
                $alt_text = isset($data['featured_image']['alt'])      ? (string)$data['featured_image']['alt']      : '';
                $this->set_featured_image($existing_id, $img_url, $filename, $alt_text);
            }
            return new WP_REST_Response([
                'id'      => $existing_id,
                'link'    => get_permalink($existing_id),
                'status'  => $post->post_status,
                'updated' => true,
            ], 200);
        }

        // Full publish / update — categories first.
        $category_ids = [];
        foreach ((array)(isset($data['categories']) ? $data['categories'] : []) as $name) {
            $name = (string)$name;
            if ($name === '') continue;
            $term = get_term_by('name', $name, 'category');
            if ($term && !is_wp_error($term)) {
                $category_ids[] = (int)$term->term_id;
            } else {
                $inserted = wp_insert_term($name, 'category');
                if (!is_wp_error($inserted) && isset($inserted['term_id'])) {
                    $category_ids[] = (int)$inserted['term_id'];
                }
            }
        }

        $allowed_statuses = ['publish', 'draft', 'pending', 'private'];
        $raw_status       = isset($data['status']) ? (string)$data['status'] : 'publish';
        $status           = in_array($raw_status, $allowed_statuses, true) ? $raw_status : 'publish';

        $post_data = [
            'post_title'    => wp_strip_all_tags(isset($data['title'])   ? (string)$data['title']   : ''),
            'post_name'     => sanitize_title(isset($data['slug'])        ? (string)$data['slug']    : ''),
            'post_content'  => isset($data['content'])  ? (string)$data['content']  : '',
            'post_excerpt'  => isset($data['excerpt'])  ? (string)$data['excerpt']  : '',
            'post_status'   => $status,
            'post_type'     => 'post',
            'post_author'   => get_current_user_id(),
            'post_category' => $category_ids,
            'tags_input'    => array_values(array_filter(array_map('strval', (array)(isset($data['tags']) ? $data['tags'] : [])))),
        ];

        if ($existing_id > 0) {
            $post_data['ID'] = $existing_id;
        }

        $post_id = wp_insert_post($post_data, true);
        if (is_wp_error($post_id)) {
            return new WP_Error('cs_publisher_insert_failed', $post_id->get_error_message(), ['status' => 500]);
        }

        foreach ((array)(isset($data['meta']) ? $data['meta'] : []) as $k => $v) {
            if (!is_string($k) || $k === '') continue;
            update_post_meta($post_id, $k, is_string($v) ? $v : wp_json_encode($v));
        }

        $img_url = isset($data['featured_image']['url']) ? $data['featured_image']['url'] : null;
        if (is_string($img_url) && $img_url !== '') {
            $filename = isset($data['featured_image']['filename'])
                ? (string)$data['featured_image']['filename']
                : (sanitize_title(isset($data['slug']) ? (string)$data['slug'] : 'featured') . '.jpg');
            $alt_text = isset($data['featured_image']['alt']) ? (string)$data['featured_image']['alt'] : '';
            $this->set_featured_image($post_id, $img_url, $filename, $alt_text);
        }

        $post = get_post($post_id);
        return new WP_REST_Response([
            'id'     => (int)$post_id,
            'link'   => get_permalink($post_id),
            'status' => $post ? $post->post_status : $status,
        ], 200);
    }
}

new CS_Publisher_v1();

endif; // class_exists('CS_Publisher_v1')
